-- =========== Customers Table ===========
CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  address TEXT,
  gstin TEXT
);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage customers" ON public.customers FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- =========== Products Table ===========
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  sku TEXT UNIQUE,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  stock_quantity INT DEFAULT 0
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage products" ON public.products FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- =========== Invoices Table ===========
CREATE TYPE invoice_status AS ENUM ('draft', 'paid', 'void');
CREATE TABLE public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invoice_number TEXT UNIQUE NOT NULL,
  invoice_date DATE NOT NULL,
  customer_id BIGINT REFERENCES public.customers(id),
  grand_total NUMERIC(10, 2) NOT NULL,
  total_gst NUMERIC(10, 2),
  status invoice_status DEFAULT 'draft',
  -- Fields for mall reporting
  business_date DATE,
  location_code TEXT,
  terminal_id TEXT,
  shift_no TEXT,
  receipt_time TIME,
  return_amount NUMERIC(10, 2),
  transaction_status TEXT,
  customer_name TEXT,
  customer_phone TEXT,
  customer_gstin TEXT
);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage invoices" ON public.invoices FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- =========== Invoice Items Table ===========
-- (This table links products to an invoice)
CREATE TABLE public.invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  product_name TEXT NOT NULL, -- Denormalized for easier reporting
  quantity INT NOT NULL,
  rate NUMERIC(10, 2) NOT NULL,
  total_price NUMERIC(10, 2) NOT NULL,
  gst_amount NUMERIC(10, 2),
  discount_amount NUMERIC(10, 2)
);
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage invoice items" ON public.invoice_items FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- =========== Invoice Payments Table ===========
-- (This table records payments for an invoice)
CREATE TABLE public.invoice_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  payment_method_name TEXT NOT NULL,
  payment_method_id TEXT,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE
);
ALTER TABLE public.invoice_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage invoice payments" ON public.invoice_payments FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');