ALTER TABLE public.products
ADD COLUMN hsn TEXT,
ADD COLUMN gst_percent NUMERIC(5, 2) NOT NULL DEFAULT 18,
ADD COLUMN purchase_price NUMERIC(10, 2),
ADD COLUMN unit TEXT NOT NULL DEFAULT 'Pcs',
ADD COLUMN low_stock_alert INT NOT NULL DEFAULT 10;
